#index:
#    path: /
#    controller: App\Controller\DefaultController::index
chatbot_home:
  path:     /chatbot/
  controller: App\Controller\ChatBotController::indexAction

chatbot_query:
  path:     /chatbot/query
  controller: App\Controller\ChatBotController::queryAction